### ISSUE TITLE
Uneven commits 

### ISSUE THREAD

**Issue by azayneeva** [fac-12/teamQEventFinder#40]
<img width="427" alt="screen shot 2017-11-24 at 10 10 06" src="https://user-images.githubusercontent.com/24795752/33205933-87596324-d100-11e7-8536-26e2f4c31e9e.png">

guys, you should aim to have more balance, so that everyone in your team contributes equally to the project

**Comment by shannonjensen** [comment]
Point taken but we are always pair programming so this isn't an accurate representation. Also, commits are of very different sizes so not really an accurate proxy of contributions either.
