### ISSUE TITLE
disable eslint for front end JS files 

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/teamQEventFinder#41]
Hey guys, 

Fantastic work as always 🎉🎉🎉🎉 

You can avoid all the annoying eslint messages on your front-end JS files by adding this at the top of the file:

`/*eslint-disable*/`

Seeing as you can't use es6 syntax on the front-end atm, you can just disable the linter 😉

**Comment by shannonjensen** [comment]
We used it when in development, then took it off but I see what you mean about front vs back with eslint
