### ISSUE TITLE
cloning an array to produce another array

### ISSUE THREAD

**Issue by Jbarget** [fac-12/teamQEventFinder#52]
In general there are 4 array methods that are used to transform arrays:
- filter (returns array)
- reduce (returns any data type)
- map (returns array)
- forEach (has no return value so will naturally introduce side-effects)

At this point: https://github.com/fac-12/teamQEventFinder/blob/master/src/logic.js#L20-L35

you're going from an array to an array so I would use a `map` to do the manipulation
```js
  var cloneEventsArray = noRepeat.slice(0, 10);
  var data =  cloneEventsArray.map(function(event) {
     return {
          name: event.name,
          url: event.url,
          imageUrl: event.images[1].url,
          etc...
     }
  }
```

**Comment by shannonjensen** [comment]
Much more elegant, thank you.
